# -*- coding: utf-8 -*-
"""sociology.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KYFn-FENyCTnNhHVgqRMAjjaFZ0NFMjN
"""

import ipywidgets as widgets
from IPython.display import display, clear_output

header = widgets.HTML("<h1><center style='color: #ad1457;'>SOCIAL BREAKDOWN BINGO</center></h1>")
subtext = widgets.HTML("<p><center><i>Are you a Sociology Rebel or a Perfectly Molded Product?</i></center></p>")

items = [
    "Home Voice vs Public Voice", "Called teacher 'Mom'", "Bell Anxiety",
    "Hidden from prof at mall", "Gendered Toys", "Grade Chaser",
    "Hand Raising at home", "Secret Family Rules", "Guilt for being late"
]


checkboxes = [widgets.Checkbox(value=False, description=item,
                               layout=widgets.Layout(width='auto', margin='10px'))
              for item in items]


grid = widgets.GridBox(checkboxes, layout=widgets.Layout(grid_template_columns="repeat(3, 300px)"))


button = widgets.Button(description="GET DIAGNOSIS",
                        button_style='info', # Cyan/Blue color
                        layout=widgets.Layout(width='50%', margin='20px 25%'))

output = widgets.Output()


def get_diagnosis(b):
    with output:
        clear_output()
        score = sum([1 for c in checkboxes if c.value])

        print(f"--- ANALYZING DATA FOR NOUR & HOUDA ---")
        print(f"SCORE: {score}/9")

        if score <= 3:
            print("RESULT: SYSTEM GLITCH DETECTED.")
            print("Diagnosis: You have resisted the Personality Factory. A true sociology rebel!")
        elif score <= 6:
            print("RESULT: STANDARD PRODUCT APPROVED.")
            print("Diagnosis: Successfully socialized. You fit the 'Society in Miniature' perfectly.")
        else:
            print("RESULT: ELITE AGENT OF CONFORMITY.")
            print("Diagnosis: Parsons and Durkheim would be proud. You ARE the system!")

button.on_click(get_diagnosis)


display(header, subtext, grid, button, output)